---
- name: Install required packages
  loop:
    - parted
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - volume

- name: Create defined partitions
  loop: "{{ volume_partitions }}"
  loop_control:
    label: "{{ item.device }}"
  community.general.parted:
    device: "{{ item.device }}"
    number: "{{ item.number }}"
    label: "{{ omit if item.label is undefined else item.label }}"
    name: "{{ 'GPT' if item.label == 'gpt' else omit }}"
    flags: "{{ item.flags | default([]) }}"
    state: "{{ item.state | default('present') }}"
    part_start: "{{ item.part_start | default('0%') }}"
    part_end: "{{ item.part_end | default('100%') }}"
    part_type: "{{ item.part_type | default('primary') }}"
    unit: "{{ item.unit | default('%') }}"
  tags:
    - volume

- name: Create defined filesystems
  loop: "{{ volume_partitions }}"
  loop_control:
    label: "{{ item.device }}"
  community.general.filesystem:
    fstype: "{{ item.filesystem }}"
    dev: "{{ item.device }}{% if item.format | default(False) == 'by-id' %}-part{% endif %}{{ item.number }}"
  tags:
    - volume

- name: Mount defined volumes
  loop: "{{ volume_partitions }}"
  loop_control:
    label: "{{ item.device }}"
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.device }}{% if item.format | default(False) == 'by-id' %}-part{% endif %}{{ item.number }}"
    fstype: "{{ item.filesystem }}"
    opts: "{{ item.options | default([]) | join(',') }}"
    state: mounted
  tags:
    - volume

...
