- name: install deps
  loop:
    - parted
  package:
    name: '{{ item }}'
    state: present
  tags:
    - volume

- name: create partitions
  loop: '{{ volume_partitions }}'
  loop_control:
    label: '{{ item.device }}'
  parted:
    device: '{{ item.device }}'
    number: '{{ item.number }}'
    flags: '{{ item.flags | default([]) }}'
    state: '{{ item.state | default("present") }}'
    part_start: '{{ item.part_start | default("0%") }}'
    part_end: '{{ item.part_end | default("100%") }}'
    part_type: '{{ item.part_type | default("primary") }}'
    unit: '{{ item.unit | default("%") }}'
  tags:
    - volume

- name: create filesystems
  loop: '{{ volume_partitions }}'
  loop_control: 
    label: 'device: {{ item.device }}{% if item.format | default("") == "by-id" %}-part{% endif %}{{ item.number }}, fs: {{ item.filesystem }}'
  filesystem:
    fstype: '{{ item.filesystem }}'
    dev: '{{ item.device }}{% if item.format | default("") == "by-id" %}-part{% endif %}{{ item.number }}'
  tags:
    - volume

- name: mount volumes
  loop: '{{ volume_partitions }}'
  loop_control:
    label: 'device: {{ item.device }}{% if item.format | default("") == "by-id" %}-part{% endif %}{{ item.number }}, path: {{ item.path }}, options: {{ item.options | default([]) | join(",") }} '
  mount:
    path: '{{ item.path }}'
    src: '{{ item.device }}{% if item.format | default("") == "by-id" %}-part{% endif %}{{ item.number }}'
    fstype: '{{ item.filesystem }}'
    opts: '{{ item.options | default([]) | join(",") }}'
    state: mounted
  tags:
    - volume
